% ACCEPT('noGui',true,'inputFolder','./data/selected_cells_her2',...
%     'outputFolder','./data/results/selected_cells_her2','customFunction','Her2_priorThumbs_Scoring.m','sampleName','priorThumbs')

ACCEPT('noGui',true,'inputFolder',[pwd '/data/selected_cells_her2'],...
    'outputFolder','./data/results/selected_cells_her2','customFunction','Her2_Thumbs_Scoring.m','sampleName','Thumbs')