ACCEPT('noGui',true,'inputFolder',['ACCEPT' filesep 'data' filesep 'selected_cells_her2'],...
    'outputFolder',['ACCEPT' filesep 'data' filesep 'results' filesep 'selected_cells_her2'],'customFunction','Her2_priorThumbs_Scoring.m','sampleName','priorThumbs')


% ACCEPT('noGui',true,'inputFolder',['ACCEPT' filesep 'data' filesep 'selected_cells_her2'],...
%     'outputFolder',['ACCEPT' filesep 'data' filesep 'results' filesep 'selected_cells_her2'],'customFunction',...
%     'Her2_Thumbs_Scoring.m','sampleName','Thumbs')